"""auto votes table

Revision ID: 6e7137ef6ae9
Revises: 6e26264769ef
Create Date: 2026-08-17 13:50:29.584837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7137ef6ae9'
down_revision = '6e26264769ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # Drop standard default and convert to IDENTITY
    op.execute("ALTER TABLE posts ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE posts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY")
    
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY")
    # ### end Alembic commands ###


def downgrade():
    # Drop IDENTITY and restore standard sequence defaults
    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq'::regclass)")
    
    op.execute("ALTER TABLE posts ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE posts ALTER COLUMN id SET DEFAULT nextval('posts_id_seq'::regclass)")
    
    op.drop_table('votes')
